2021-03-18 15:25:01,140 : INFO : root : Loading config.
2021-03-18 15:25:01,147 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2021-03-18 15:25:01,147 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Noah\work\Andy Cavatorta\pinball\notes\MPF\noahgame_02\config\config.yaml
2021-03-18 15:25:01,148 : INFO : ConfigProcessor : Loading config from file c:\users\noah\mpfenv\lib\site-packages\mpf\mpfconfig.yaml.
2021-03-18 15:25:01,279 : INFO : ConfigProcessor : Loading config: c:\users\noah\mpfenv\lib\site-packages\mpf\mpfconfig.yaml
2021-03-18 15:25:01,281 : INFO : ConfigProcessor : Loading config from file C:\Users\Noah\work\Andy Cavatorta\pinball\notes\MPF\noahgame_02\config\config.yaml.
2021-03-18 15:25:01,321 : INFO : ConfigProcessor : Loading config: C:\Users\Noah\work\Andy Cavatorta\pinball\notes\MPF\noahgame_02\config\config.yaml
2021-03-18 15:25:01,324 : INFO : ConfigProcessor : Config file cache created: C:\Users\Noah\AppData\Local\Temp\d1f6a309ab2e3c3e66b0fef93f7a960f.mpf_cache
2021-03-18 15:25:01,444 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Noah\AppData\Local\Temp\74774f186c18434d8d39d0d4b0a3afeb.mpf_cache
2021-03-18 15:25:01,445 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Noah\AppData\Local\Temp\a7eac71e9da1e9cfd4db34c71351dbda.mpf_cache
2021-03-18 15:25:01,445 : INFO : Machine : Mission Pinball Framework Core Engine v0.54.6
2021-03-18 15:25:01,445 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2021-03-18-15-25-01-mpf-DESKTOP-VL0THH1.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2021-03-18 15:25:01,445 : INFO : Machine : MPF path: c:\users\noah\mpfenv\lib\site-packages\mpf
2021-03-18 15:25:01,445 : INFO : Machine : Machine path: C:\Users\Noah\work\Andy Cavatorta\pinball\notes\MPF\noahgame_02
2021-03-18 15:25:01,446 : INFO : Machine : Platform: win32
2021-03-18 15:25:01,446 : INFO : Machine : Python executable location: c:\users\noah\mpfenv\scripts\python.exe
2021-03-18 15:25:01,446 : INFO : Machine : Python version: 3.7.9 (64-bit)
2021-03-18 15:25:01,449 : INFO : Machine : Initialise MPF.
2021-03-18 15:25:01,565 : INFO : P-Roc : Connecting to P-ROC
2021-03-18 15:25:01,572 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): FT_ListDevices(2)
. Is your P/P3-Roc connected and powered up?
2021-03-18 15:25:01,572 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2021-03-18 15:25:02,576 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): FT_ListDevices(2)
. Is your P/P3-Roc connected and powered up?
2021-03-18 15:25:02,576 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2021-03-18 15:25:03,578 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): FT_ListDevices(2)
. Is your P/P3-Roc connected and powered up?
2021-03-18 15:25:03,578 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2021-03-18 15:25:05,737 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Error reading Chip IP and Version. Read 7 words instead of 5. The first 2 were: 0x0 and 0x0.. Is your P/P3-Roc connected and powered up?
2021-03-18 15:25:05,737 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2021-03-18 15:25:06,936 : INFO : P-Roc : Successfully connected to P-ROC/P3-ROC. Firmware Version: 2. Firmware Revision: 6. Hardware Board ID: 1
2021-03-18 15:25:06,936 : WARNING : P-Roc : Consider upgrading the firmware of your P/P3-Roc to at least 2.14. Your version contains known bugs.
2021-03-18 15:25:06,997 : INFO : EventManager : Event: ======'machine_var_p_roc_version'====== Args={'value': 2, 'prev_value': None, 'change': True}
2021-03-18 15:25:06,997 : INFO : EventManager : Event: ======'machine_var_p_roc_revision'====== Args={'value': 6, 'prev_value': None, 'change': True}
2021-03-18 15:25:06,997 : INFO : EventManager : Event: ======'machine_var_p_roc_hardware_version'====== Args={'value': 1, 'prev_value': None, 'change': True}
2021-03-18 15:25:06,998 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2021-03-18 15:25:07,079 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.54.6', 'prev_value': None, 'change': True}
2021-03-18 15:25:07,079 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.54.6, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2021-03-18 15:25:07,079 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.7.9', 'prev_value': None, 'change': True}
2021-03-18 15:25:07,079 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19041-SP0', 'prev_value': None, 'change': True}
2021-03-18 15:25:07,079 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2021-03-18 15:25:07,079 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2021-03-18 15:25:07,079 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19041', 'prev_value': None, 'change': True}
2021-03-18 15:25:07,079 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2021-03-18 15:25:07,079 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2021-03-18 15:25:07,102 : ERROR : ConfigValidator : Your config contains a value for the setting "drop_target_banks:noah:enable_events", but this is not a valid setting name.
2021-03-18 15:25:07,103 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...tting name.')>) at c:\users\noah\mpfenv\lib\site-packages\mpf\core\events.py:111
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...tting name.')>) at c:\users\noah\mpfenv\lib\site-packages\mpf\core\events.py:111>
Traceback (most recent call last):
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\events.py", line 114, in _async_handler_done
    future.result()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\device_manager.py", line 100, in _load_device_modules
    self.load_devices_config(validate=True)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\device_manager.py", line 164, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\device.py", line 104, in validate_and_parse_config
    self.config_section, config, self.name, "device", prefix=debug_prefix)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 176, in validate_config
    validation_failure_info=validation_failure_info)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 188, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 355, in check_for_invalid_sections
    'setting name.', 2, self.log.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Your config contains a value for the setting "drop_target_banks:noah:enable_events", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://docs.missionpinball.org/en/0.54/logs/CFE-ConfigValidator-2.html)
2021-03-18 15:25:07,108 : INFO : Machine : Starting the main run loop.
2021-03-18 15:25:07,108 : INFO : Machine : Shutting down...
2021-03-18 15:25:07,108 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2021-03-18 15:25:07,111 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\machine.py", line 745, in _run_loop
    raise self._exception['exception']
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\events.py", line 114, in _async_handler_done
    future.result()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\device_manager.py", line 100, in _load_device_modules
    self.load_devices_config(validate=True)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\device_manager.py", line 164, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\device.py", line 104, in validate_and_parse_config
    self.config_section, config, self.name, "device", prefix=debug_prefix)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 176, in validate_config
    validation_failure_info=validation_failure_info)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 188, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 355, in check_for_invalid_sections
    'setting name.', 2, self.log.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Your config contains a value for the setting "drop_target_banks:noah:enable_events", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://docs.missionpinball.org/en/0.54/logs/CFE-ConfigValidator-2.html)
2021-03-18 15:25:07,113 : INFO : root : MPF run loop ended.
