2021-03-18 15:07:16,695 : INFO : root : Loading config.
2021-03-18 15:07:16,702 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2021-03-18 15:07:16,703 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Noah\work\Andy Cavatorta\pinball\notes\MPF\noahgame_02\config\config.yaml
2021-03-18 15:07:16,703 : INFO : ConfigProcessor : Loading config from file c:\users\noah\mpfenv\lib\site-packages\mpf\mpfconfig.yaml.
2021-03-18 15:07:16,830 : INFO : ConfigProcessor : Loading config: c:\users\noah\mpfenv\lib\site-packages\mpf\mpfconfig.yaml
2021-03-18 15:07:16,832 : INFO : ConfigProcessor : Loading config from file C:\Users\Noah\work\Andy Cavatorta\pinball\notes\MPF\noahgame_02\config\config.yaml.
2021-03-18 15:07:16,864 : INFO : ConfigProcessor : Loading config: C:\Users\Noah\work\Andy Cavatorta\pinball\notes\MPF\noahgame_02\config\config.yaml
2021-03-18 15:07:16,867 : INFO : ConfigProcessor : Config file cache created: C:\Users\Noah\AppData\Local\Temp\d1f6a309ab2e3c3e66b0fef93f7a960f.mpf_cache
2021-03-18 15:07:16,997 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Noah\AppData\Local\Temp\74774f186c18434d8d39d0d4b0a3afeb.mpf_cache
2021-03-18 15:07:16,998 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Noah\AppData\Local\Temp\a7eac71e9da1e9cfd4db34c71351dbda.mpf_cache
2021-03-18 15:07:17,000 : INFO : Machine : Mission Pinball Framework Core Engine v0.54.6
2021-03-18 15:07:17,000 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2021-03-18-15-07-16-mpf-DESKTOP-VL0THH1.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2021-03-18 15:07:17,000 : INFO : Machine : MPF path: c:\users\noah\mpfenv\lib\site-packages\mpf
2021-03-18 15:07:17,000 : INFO : Machine : Machine path: C:\Users\Noah\work\Andy Cavatorta\pinball\notes\MPF\noahgame_02
2021-03-18 15:07:17,001 : INFO : Machine : Platform: win32
2021-03-18 15:07:17,001 : INFO : Machine : Python executable location: c:\users\noah\mpfenv\scripts\python.exe
2021-03-18 15:07:17,001 : INFO : Machine : Python version: 3.7.9 (64-bit)
2021-03-18 15:07:17,004 : INFO : Machine : Initialise MPF.
2021-03-18 15:07:17,135 : INFO : P-Roc : Connecting to P-ROC
2021-03-18 15:07:17,349 : INFO : P-Roc : Successfully connected to P-ROC/P3-ROC. Firmware Version: 2. Firmware Revision: 6. Hardware Board ID: 1
2021-03-18 15:07:17,349 : WARNING : P-Roc : Consider upgrading the firmware of your P/P3-Roc to at least 2.14. Your version contains known bugs.
2021-03-18 15:07:17,421 : INFO : EventManager : Event: ======'machine_var_p_roc_version'====== Args={'value': 2, 'prev_value': None, 'change': True}
2021-03-18 15:07:17,421 : INFO : EventManager : Event: ======'machine_var_p_roc_revision'====== Args={'value': 6, 'prev_value': None, 'change': True}
2021-03-18 15:07:17,421 : INFO : EventManager : Event: ======'machine_var_p_roc_hardware_version'====== Args={'value': 1, 'prev_value': None, 'change': True}
2021-03-18 15:07:17,422 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2021-03-18 15:07:17,508 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.54.6', 'prev_value': None, 'change': True}
2021-03-18 15:07:17,509 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.54.6, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2021-03-18 15:07:17,509 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.7.9', 'prev_value': None, 'change': True}
2021-03-18 15:07:17,509 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19041-SP0', 'prev_value': None, 'change': True}
2021-03-18 15:07:17,509 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2021-03-18 15:07:17,509 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2021-03-18 15:07:17,509 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19041', 'prev_value': None, 'change': True}
2021-03-18 15:07:17,509 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2021-03-18 15:07:17,509 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2021-03-18 15:07:17,533 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...our config.')>) at c:\users\noah\mpfenv\lib\site-packages\mpf\core\events.py:111
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...our config.')>) at c:\users\noah\mpfenv\lib\site-packages\mpf\core\events.py:111>
Traceback (most recent call last):
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\events.py", line 114, in _async_handler_done
    future.result()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\device_manager.py", line 100, in _load_device_modules
    self.load_devices_config(validate=True)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\device_manager.py", line 164, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\device.py", line 104, in validate_and_parse_config
    self.config_section, config, self.name, "device", prefix=debug_prefix)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 176, in validate_config
    validation_failure_info=validation_failure_info)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 218, in _validate_config
    validation_failure_info=ValidationPath(validation_failure_info, k))
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 266, in validate_config_item
    new_list.append(self.validate_item(i, validation, validation_failure_info))
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 699, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 415, in _validate_type_machine
    6)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 718, in validation_error
    item, msg), 5 if code is None else code, self.log.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry drop_target_banks:noah:drop_targets = "s_drop_target" is not valid. Device "s_drop_target" not found in "drop_targets:" section in your config. Error Code: CFE-ConfigValidator-6 (https://docs.missionpinball.org/en/0.54/logs/CFE-ConfigValidator-6.html)
2021-03-18 15:07:17,591 : INFO : Machine : Starting the main run loop.
2021-03-18 15:07:17,591 : INFO : Machine : Shutting down...
2021-03-18 15:07:17,592 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2021-03-18 15:07:17,595 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\machine.py", line 745, in _run_loop
    raise self._exception['exception']
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\events.py", line 114, in _async_handler_done
    future.result()
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\device_manager.py", line 100, in _load_device_modules
    self.load_devices_config(validate=True)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\device_manager.py", line 164, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\device.py", line 104, in validate_and_parse_config
    self.config_section, config, self.name, "device", prefix=debug_prefix)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 176, in validate_config
    validation_failure_info=validation_failure_info)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 218, in _validate_config
    validation_failure_info=ValidationPath(validation_failure_info, k))
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 266, in validate_config_item
    new_list.append(self.validate_item(i, validation, validation_failure_info))
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 699, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 415, in _validate_type_machine
    6)
  File "c:\users\noah\mpfenv\lib\site-packages\mpf\core\config_validator.py", line 718, in validation_error
    item, msg), 5 if code is None else code, self.log.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry drop_target_banks:noah:drop_targets = "s_drop_target" is not valid. Device "s_drop_target" not found in "drop_targets:" section in your config. Error Code: CFE-ConfigValidator-6 (https://docs.missionpinball.org/en/0.54/logs/CFE-ConfigValidator-6.html)
2021-03-18 15:07:17,610 : INFO : root : MPF run loop ended.
